### PR TITLE
range will not reset itself, it will adapter user's selecting operation

### PR DESCRIPTION
**Pull request by seelikes**
… by NestedScrollView

when CalendarPickerView was contained by NestedScorllView, it can only show its first child, this is one candidate solution.

### CODE REVIEW

**Comment by seelikes** [comment]
when we select dates in range mode, it is normal that we modify our selection from date to date. it's a better experience that the selected range adapt the user's change rather than reset itself.

**Comment by seelikes** [comment]
when selected date's distance to start and end is equal, set the selected date as new range's end rather than start. i think this is a better experience than set the selected date as the new range's end.

**Comment by seelikes** [comment]
solve that when we click a date before former start date, the new start date remains unselected.
if we click the date of the border date, start or end, the other edge's date will be called with unselected, but the current one will not be called with unselected. this may not be the same performance as before, i think i will consider to restore the former performance if someone complains about this.

**Comment by savvisingh** [comment]
Hey there, can you create another pull request from a branch, so I can try the code before merging it?

**Comment by seelikes** [comment]
@savvisingh ok

**Pull request closed without merging**
