### PR TITLE
Added subtitles

### PR DESCRIPTION
**Pull request by theapache64**
To show subtitles below the date, (useful for ticket booking system to show prices for specific type, such as flight price, bus price etc. of that specific day) I've [added a builder method](https://github.com/theapache64/DateRangePicker/blob/570103e4fd7192229ebb38c5cb7580e7c96df3a3/rangedatepicker/src/main/java/com/savvi/rangedatepicker/CalendarPickerView.java#L331) to `FluentInitializer`.

**Example**

```
calendar.init() 
...
.withSubTitles(getSubTitles())
...

private ArrayList<SubTitle> getSubTitles() {
        final ArrayList<SubTitle> subTitles = new ArrayList<>();
        final Calendar tmrw = Calendar.getInstance();
        tmrw.add(Calendar.DAY_OF_MONTH, 1);
        subTitles.add(new SubTitle(tmrw.getTime(), "₹1000"));
        return subTitles;
}

```
**Output**

image

### CODE REVIEW

**Comment by savvisingh** [comment]
Thanks for this awesome feature, will review it this coming weekend

**Comment by sebastian989** [comment]
I think it's a wonderful feature... Is there any news about this PR?.

Thanks in advance.

**Comment by savvisingh** [comment]
Hi @theapache64, Can you please remove your .gradle and .idea folders from the repo, its giving conflicts.
Try using my .gitignore from master

**Comment by theapache64** [comment]
Sure.

**Comment by theapache64** [comment]
@savvisingh I've updated the my .gitignore. Sorry for the mistake.

**Comment by savvisingh** [comment]
Check the latest version of the lib I have published your PR in it.
And Thanks for such a cool feature

**Comment by theapache64** [comment]
Hey,

I just signed the petition "Prime Minister of India Shri Narendra Modi:
Amendment in wildlife protection act to curb poaching and killing of
endengered animals." and wanted to see if you could help by adding your
name.

Our goal is to reach 50,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/Z8R2rCH5bD

Thanks!
Mohammed

**Pull request merged**
